apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration-service
  name: integration-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    app: integration-service
  type: LoadBalancer