apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: activity-service
  labels:
    app: activity-service
    part-of: new-icons
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: activity-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80