apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-service
  labels:
    app: socket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: socket-service
    spec:
      volumes:
        - name: config
          secret:
            secretName: pubsub-sa
      containers:
      - name: socket-service
        image: gcr.io/new-icons-jtb-dev/socket-service:77b016d9-a513-4eb6-903a-5e99fe79071d
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        envFrom:
        - configMapRef:
            name: socket-service-config
        - secretRef:
            name: user-service-secret
        volumeMounts:
          - name: config
            mountPath: '/src/src/config/pubsub-sa.json'
            subPath: 'pubsub-sa.json'
