apiVersion: v1
kind: ConfigMap
metadata:
  name: api-management-service-config
  labels:
    app: api-management-service
data:
  GCLOUD_PROJECT: new-icons-jtb-prod
  NODE_ENV: production
  PORT: "8080"
  MOUNT_BUCKET: new-icons-jtb-static-file-prod
  EXPRESS_GATEWAY: "http://api-gateway-dev/api-endpoints/"