apiVersion: v1
kind: Secret
metadata:
  name: shipping-service-secret
  labels:
    app: shipping-service
type: Opaque
data:
  DB_PASSWORD: NXp2T09oQU5Gcw==
  DB_USER: c2hpcHBpbmctc2VydmljZQ==