apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-service
  labels:
    app: po-service
    part-of: new-icons
    tier: backend
spec:
  selector:
    matchLabels:
      app: po-service
      part-of: new-icons
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: po-service
        part-of: new-icons
        tier: backend
    spec:
      volumes:
        - name: config
          secret:
            secretName: pubsub-sa
      containers:
      - name: po-service
        image: "gcr.io/new-icons-jtb-dev/po-service:891cfe8b-99aa-45c8-871d-8553c2e72f21"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: po-service-config
        - secretRef:
            name: po-service-secret
        volumeMounts:
          - name: config
            mountPath: '/src/src/config/pubsub-sa.json'
            subPath: 'pubsub-sa.json'
 
