apiVersion: v1
kind: Service
metadata:
  labels:
    app: po-service
  name: po-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: po-service
  type: NodePort