apiVersion: v1
kind: Secret
metadata:
  name: data-pump-secret
  labels:
    app: data-pump
type: Opaque
data:
  DB_SOURCE_USERNAME: cm9vdA==
  DB_SOURCE_PASSWORD: U3VQRXIhTG9Daw==

  DB_DESTINATION_USERNAME: c3Bvb2wtc2VydmljZQ==
  DB_DESTINATION_PASSWORD: cmVraW5kLXNwb29sLXNlcnZpY2U=