apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: icons-web
  labels:
    name: icons-web
    part-of: new-icons
    tier: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: icons-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80