apiVersion: apps/v1
kind: Deployment
metadata:
  name: expediting-service
  labels:
    app: expediting-service
    part-of: new-icons
    tier: backend
spec:
  selector:
    matchLabels:
      app: expediting-service
      part-of: new-icons
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expediting-service
        part-of: new-icons
        tier: backend
    spec:
      volumes:
        - name: config
          secret:
            secretName: pubsub-sa
      containers:
      - name: expediting-service
        image: "gcr.io/new-icons-jtb-dev/expediting-service:7cf8c8a7-dde2-405b-aba1-2bbdaeed7796"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: 256Mi
            cpu: 500m
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: expediting-service-config
        - secretRef:
            name: expediting-service-secret
        volumeMounts:
          - name: config
            mountPath: '/src/src/config/pubsub-sa.json'
            subPath: 'pubsub-sa.json'
