apiVersion: v1
kind: ConfigMap
metadata:
  name: test-package-service-config
  labels:
    app: test-package-service
data:
  DB_HOST: 10.42.16.2
  DB_INSTANCE: new-icons-jtb-dev:asia-southeast2:new-icons-dev
  DB_NAME: package_service
  GCLOUD_PROJECT: new-icons-jtb-prod
  NODE_ENV: production
  PORT: "8080"
  MOUNT_BUCKET: new-icons-jtb-static-file-prod
  GCS_TP_EXPORT_URL: https://storage.googleapis.com/new-icons-jtb-static-file-prod/test-package-service/